import {
  Assessment,
  AttachMoney,
  ShowChart,
  AccountBalance,
  Inventory,
  TrendingUp,
  Store,
  PieChart,
} from "@mui/icons-material";
import { KPIConfig, Category } from "./types";

export const categories: Category[] = [
  {
    key: "volume",
    label: "Volume Metrics",
    icon: <Inventory />,
    color: "#3B82F6",
  },
  {
    key: "kc",
    label: "KC Metrics",
    icon: <TrendingUp />,
    color: "#10B981",
  },
  {
    key: "retailer",
    label: "Retailer Metrics",
    icon: <Store />,
    color: "#F59E0B",
  },
  {
    key: "profit",
    label: "Profit Metrics",
    icon: <PieChart />,
    color: "#8B5CF6",
  },
];

export const kpiConfigs: KPIConfig[] = [
  // Volume Section
  {
    key: "bvol_pk",
    label: "Base Volume in Packs",
    category: "volume",
    icon: <Assessment />,
    color: "#3B82F6",
  },
  {
    key: "bvol_su",
    label: "Base Volume in SU",
    category: "volume",
    icon: <Assessment />,
    color: "#3B82F6",
  },
  {
    key: "pvol_pk",
    label: "Promo Volume in Packs",
    category: "volume",
    icon: <Assessment />,
    color: "#3B82F6",
  },
  {
    key: "pvol_su",
    label: "Promo Volume in SU",
    category: "volume",
    icon: <Assessment />,
    color: "#3B82F6",
  },
  {
    key: "tvol_pk",
    label: "Total Volume in Packs",
    category: "volume",
    icon: <Assessment />,
    color: "#3B82F6",
  },
  {
    key: "tvol_su",
    label: "Volume Growth %",
    category: "volume",
    icon: <Assessment />,
    color: "#3B82F6",
  },
  {
    key: "tvol_su_new",
    label: "Total New Volume in SU",
    category: "volume",
    icon: <Assessment />,
    color: "#3B82F6",
  },
  {
    key: "tvol_su_d_abs",
    label: "Volume Growth (abs)",
    category: "volume",
    icon: <Assessment />,
    color: "#3B82F6",
  },
  {
    key: "tvol_su_d_per",
    label: "Volume delta perc in SU",
    unit: "%",
    isPercentage: true,
    category: "volume",
    icon: <Assessment />,
    color: "#3B82F6",
  },
  {
    key: "vsod_pk",
    label: "Volume Sold On Deal in Packs (%)",
    unit: "%",
    isPercentage: true,
    category: "volume",
    icon: <Assessment />,
    color: "#3B82F6",
  },
  {
    key: "vsod_su",
    label: "Volume Sold On Deal in SU (%)",
    unit: "%",
    isPercentage: true,
    category: "volume",
    icon: <Assessment />,
    color: "#3B82F6",
  },

  // KC Metrics Section
  {
    key: "tnsv_su",
    label: "Total net sale value in SU",
    unit: "£",
    isCurrency: true,
    category: "kc",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "tns",
    label: "Total Net Sales",
    unit: "£",
    isCurrency: true,
    category: "kc",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "tns_new",
    label: "New Net Sales",
    unit: "£",
    isCurrency: true,
    category: "kc",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "tns_d_abs",
    label: "Net Sales delta abs",
    unit: "£",
    isCurrency: true,
    category: "kc",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "tns_d_per",
    label: "Net Sales delta perc",
    unit: "%",
    isPercentage: true,
    category: "kc",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "tcogs_su",
    label: "Total cost of products in SU",
    unit: "£",
    isCurrency: true,
    category: "kc",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "tcogs",
    label: "Total COGS",
    unit: "£",
    isCurrency: true,
    category: "kc",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "tgp_su",
    label: "Total GP in SU",
    unit: "£",
    isCurrency: true,
    category: "kc",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "tgp_pk",
    label: "Total GP in Pack",
    unit: "£",
    isCurrency: true,
    category: "kc",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "tgp",
    label: "Total GP",
    unit: "£",
    isCurrency: true,
    category: "kc",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "tgp_new",
    label: "Total new GP",
    unit: "£",
    isCurrency: true,
    category: "kc",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "tgp_d_abs",
    label: "GP delta abs",
    unit: "£",
    isCurrency: true,
    category: "kc",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "tgp_d_per",
    label: "GP delta perc",
    unit: "%",
    isPercentage: true,
    category: "kc",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "tgpm",
    label: "Total GPM",
    unit: "%",
    isPercentage: true,
    category: "kc",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "tgpm_new",
    label: "Total New GPM",
    unit: "%",
    isPercentage: true,
    category: "kc",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "tgpm_d_abs",
    label: "GPM delta abs",
    unit: "%",
    isPercentage: true,
    category: "kc",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "tgpm_d_per",
    label: "GPM delta perc",
    unit: "%",
    isPercentage: true,
    category: "kc",
    icon: <AttachMoney />,
    color: "#10B981",
  },

  // Retailer Metrics Section
  {
    key: "brsv_su",
    label: "Base RSV in SU",
    unit: "£",
    isCurrency: true,
    category: "retailer",
    icon: <ShowChart />,
    color: "#F59E0B",
  },
  {
    key: "brsv_pk",
    label: "Base RSV in Pack",
    unit: "£",
    isCurrency: true,
    category: "retailer",
    icon: <ShowChart />,
    color: "#F59E0B",
  },
  {
    key: "prsv_su",
    label: "Promo RSV in SU",
    unit: "£",
    isCurrency: true,
    category: "retailer",
    icon: <ShowChart />,
    color: "#F59E0B",
  },
  {
    key: "prsv_pk",
    label: "Promo RSV in Pack",
    unit: "£",
    isCurrency: true,
    category: "retailer",
    icon: <ShowChart />,
    color: "#F59E0B",
  },
  {
    key: "trsv",
    label: "Total RSV",
    unit: "£",
    isCurrency: true,
    category: "retailer",
    icon: <ShowChart />,
    color: "#F59E0B",
  },
  {
    key: "trsv_new",
    label: "Total New RSV",
    unit: "£",
    isCurrency: true,
    category: "retailer",
    icon: <ShowChart />,
    color: "#F59E0B",
  },
  {
    key: "trsv_d_abs",
    label: "RSV delta abs",
    unit: "£",
    isCurrency: true,
    category: "retailer",
    icon: <ShowChart />,
    color: "#F59E0B",
  },
  {
    key: "trsv_d_per",
    label: "RSV delta perc",
    unit: "%",
    isPercentage: true,
    category: "retailer",
    icon: <ShowChart />,
    color: "#F59E0B",
  },
  {
    key: "trp",
    label: "Total Retailer Profit",
    unit: "£",
    isCurrency: true,
    category: "retailer",
    icon: <ShowChart />,
    color: "#F59E0B",
  },
  {
    key: "trp_new",
    label: "Total New Retailer Profit",
    unit: "£",
    isCurrency: true,
    category: "retailer",
    icon: <ShowChart />,
    color: "#F59E0B",
  },
  {
    key: "trp_d_abs",
    label: "Retailer Growth (abs)",
    unit: "£",
    isCurrency: true,
    category: "retailer",
    icon: <ShowChart />,
    color: "#F59E0B",
  },
  {
    key: "trp_d_per",
    label: "Retailer profit delta perc",
    unit: "%",
    isPercentage: true,
    category: "retailer",
    icon: <ShowChart />,
    color: "#F59E0B",
  },
  {
    key: "trpm",
    label: "Total Retailer Profit Margin",
    unit: "%",
    isPercentage: true,
    category: "retailer",
    icon: <ShowChart />,
    color: "#F59E0B",
  },
  {
    key: "trpm_new",
    label: "Total New Retailer Profit Margin",
    unit: "%",
    isPercentage: true,
    category: "retailer",
    icon: <ShowChart />,
    color: "#F59E0B",
  },
  {
    key: "trpm_d_abs",
    label: "RPM delta abs",
    unit: "%",
    isPercentage: true,
    category: "retailer",
    icon: <ShowChart />,
    color: "#F59E0B",
  },
  {
    key: "trpm_d_per",
    label: "RPM delta perc",
    unit: "%",
    isPercentage: true,
    category: "retailer",
    icon: <ShowChart />,
    color: "#F59E0B",
  },
  {
    key: "trp_su",
    label: "Total Retailer Profit in SU",
    unit: "£",
    isCurrency: true,
    category: "retailer",
    icon: <ShowChart />,
    color: "#F59E0B",
  },
  {
    key: "trp_pk",
    label: "Total Retailer Profit in Pack",
    unit: "£",
    isCurrency: true,
    category: "retailer",
    icon: <ShowChart />,
    color: "#F59E0B",
  },

  // Profit Pool Section
  {
    key: "tpp",
    label: "Total Profit (abs)",
    unit: "£",
    isCurrency: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "tpp_new",
    label: "New Total Profit Pool",
    unit: "£",
    isCurrency: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "tpp_d_abs",
    label: "TPP delta abs",
    unit: "£",
    isCurrency: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "tpp_d_per",
    label: "TPP delta perc",
    unit: "%",
    isPercentage: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "tkcpp",
    label: "Total KC (abs)",
    unit: "£",
    isCurrency: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "tkcpp_new",
    label: "New Total KC Profit Pool",
    unit: "£",
    isCurrency: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "tkcpp_d_abs",
    label: "KC Growth (abs)",
    unit: "£",
    isCurrency: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "tkcpp_d_per",
    label: "KC Profit Pool delta perc",
    unit: "%",
    isPercentage: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "trpp",
    label: "Total Retailer Profit Pool",
    unit: "£",
    isCurrency: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "trpp_new",
    label: "New Total Retailer Profit Pool",
    unit: "£",
    isCurrency: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "trpp_d_abs",
    label: "Retailer PP delta abs",
    unit: "£",
    isCurrency: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "trpp_d_per",
    label: "Retailer PP delta perc",
    unit: "%",
    isPercentage: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
];
