import {
  Assessment,
  AttachMoney,
  ShowChart,
  AccountBalance,
} from "@mui/icons-material";
import { KPIConfig, Category } from "./types";

export const categories: Category[] = [
  {
    key: "volume",
    label: "Volume Metrics",
    icon: <Assessment />,
    color: "#3B82F6",
  },
  {
    key: "financial",
    label: "Financial Metrics",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "margin",
    label: "Margin Metrics",
    icon: <ShowChart />,
    color: "#F59E0B",
  },
  {
    key: "profit",
    label: "Profit Metrics",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
];

export const kpiConfigs: KPIConfig[] = [
  // Volume KPIs
  {
    key: "bvol_pk",
    label: "Base Volume in Packs",
    category: "volume",
    icon: <Assessment />,
    color: "#3B82F6",
  },
  {
    key: "bvol_su",
    label: "Base Volume in SU",
    category: "volume",
    icon: <Assessment />,
    color: "#3B82F6",
  },
  {
    key: "pvol_pk",
    label: "Promo Volume in Packs",
    category: "volume",
    icon: <Assessment />,
    color: "#3B82F6",
  },
  {
    key: "pvol_su",
    label: "Promo Volume in SU",
    category: "volume",
    icon: <Assessment />,
    color: "#3B82F6",
  },
  {
    key: "tvol_pk",
    label: "Total Volume in Packs",
    category: "volume",
    icon: <Assessment />,
    color: "#3B82F6",
  },
  {
    key: "tvol_su",
    label: "Total Volume in SU",
    category: "volume",
    icon: <Assessment />,
    color: "#3B82F6",
  },
  {
    key: "tvol_su_d_abs",
    label: "Volume SU Change (Abs)",
    category: "volume",
    icon: <Assessment />,
    color: "#3B82F6",
  },
  {
    key: "tvol_su_d_per",
    label: "Volume SU Change (%)",
    unit: "%",
    isPercentage: true,
    category: "volume",
    icon: <Assessment />,
    color: "#3B82F6",
  },
  {
    key: "tvol_su_new",
    label: "New Volume SU",
    category: "volume",
    icon: <Assessment />,
    color: "#3B82F6",
  },
  {
    key: "vsod_pk",
    label: "Volume Sold On Deal Packs (%)",
    unit: "%",
    isPercentage: true,
    category: "volume",
    icon: <Assessment />,
    color: "#3B82F6",
  },
  {
    key: "vsod_su",
    label: "Volume Sold On Deal SU (%)",
    unit: "%",
    isPercentage: true,
    category: "volume",
    icon: <Assessment />,
    color: "#3B82F6",
  },

  // Financial KPIs
  {
    key: "tns",
    label: "Total Net Sales",
    unit: "£",
    isCurrency: true,
    category: "financial",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "tns_d_abs",
    label: "Net Sales Change (Abs)",
    unit: "£",
    isCurrency: true,
    category: "financial",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "tns_d_per",
    label: "Net Sales Change (%)",
    unit: "%",
    isPercentage: true,
    category: "financial",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "tns_new",
    label: "New Net Sales",
    unit: "£",
    isCurrency: true,
    category: "financial",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "tnsv_su",
    label: "Total NSV/SU",
    unit: "£",
    isCurrency: true,
    category: "financial",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "trsv",
    label: "Total RSV",
    unit: "£",
    isCurrency: true,
    category: "financial",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "trsv_d_abs",
    label: "RSV Change (Abs)",
    unit: "£",
    isCurrency: true,
    category: "financial",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "trsv_d_per",
    label: "RSV Change (%)",
    unit: "%",
    isPercentage: true,
    category: "financial",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "trsv_new",
    label: "New RSV",
    unit: "£",
    isCurrency: true,
    category: "financial",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "tcogs",
    label: "Total COGS",
    unit: "£",
    isCurrency: true,
    category: "financial",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "tcogs_su",
    label: "Total COGS/SU",
    unit: "£",
    isCurrency: true,
    category: "financial",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "brsv_pk",
    label: "Base RSV/Pack",
    unit: "£",
    isCurrency: true,
    category: "financial",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "brsv_su",
    label: "Base RSV/SU (excl VAT)",
    unit: "£",
    isCurrency: true,
    category: "financial",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "prsv_pk",
    label: "Promo RSV/Pack",
    unit: "£",
    isCurrency: true,
    category: "financial",
    icon: <AttachMoney />,
    color: "#10B981",
  },
  {
    key: "prsv_su",
    label: "Promo RSV/SU",
    unit: "£",
    isCurrency: true,
    category: "financial",
    icon: <AttachMoney />,
    color: "#10B981",
  },

  // Margin KPIs
  {
    key: "tgp",
    label: "Total Gross Profit",
    unit: "£",
    isCurrency: true,
    category: "margin",
    icon: <ShowChart />,
    color: "#F59E0B",
  },
  {
    key: "tgp_d_abs",
    label: "Total GP Change (Abs)",
    unit: "£",
    isCurrency: true,
    category: "margin",
    icon: <ShowChart />,
    color: "#F59E0B",
  },
  {
    key: "tgp_d_per",
    label: "Total GP Change (%)",
    unit: "%",
    isPercentage: true,
    category: "margin",
    icon: <ShowChart />,
    color: "#F59E0B",
  },
  {
    key: "tgp_new",
    label: "New Total GP",
    unit: "£",
    isCurrency: true,
    category: "margin",
    icon: <ShowChart />,
    color: "#F59E0B",
  },
  {
    key: "tgp_pk",
    label: "Total GP/Pack",
    unit: "£",
    isCurrency: true,
    category: "margin",
    icon: <ShowChart />,
    color: "#F59E0B",
  },
  {
    key: "tgp_su",
    label: "Total GP/SU",
    unit: "£",
    isCurrency: true,
    category: "margin",
    icon: <ShowChart />,
    color: "#F59E0B",
  },
  {
    key: "tgpm",
    label: "Total GP Margin (%)",
    unit: "%",
    isPercentage: true,
    category: "margin",
    icon: <ShowChart />,
    color: "#F59E0B",
  },
  {
    key: "tgpm_d_abs",
    label: "GP Margin Change (Abs)",
    unit: "%",
    isPercentage: true,
    category: "margin",
    icon: <ShowChart />,
    color: "#F59E0B",
  },
  {
    key: "tgpm_d_per",
    label: "GP Margin Change (%)",
    unit: "%",
    isPercentage: true,
    category: "margin",
    icon: <ShowChart />,
    color: "#F59E0B",
  },
  {
    key: "tgpm_new",
    label: "New GP Margin (%)",
    unit: "%",
    isPercentage: true,
    category: "margin",
    icon: <ShowChart />,
    color: "#F59E0B",
  },

  // Profit KPIs
  {
    key: "trp",
    label: "Total Retailer Profit",
    unit: "£",
    isCurrency: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "trp_d_abs",
    label: "Retailer Profit Change (Abs)",
    unit: "£",
    isCurrency: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "trp_d_per",
    label: "Retailer Profit Change (%)",
    unit: "%",
    isPercentage: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "trp_new",
    label: "New Retailer Profit",
    unit: "£",
    isCurrency: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "trp_pk",
    label: "Retailer Profit/Pack",
    unit: "£",
    isCurrency: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "trp_su",
    label: "Retailer Profit/SU",
    unit: "£",
    isCurrency: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "trpm",
    label: "Retailer Profit Margin (%)",
    unit: "%",
    isPercentage: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "trpm_d_abs",
    label: "Retailer Profit Margin Change (Abs)",
    unit: "%",
    isPercentage: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "trpm_d_per",
    label: "Retailer Profit Margin Change (%)",
    unit: "%",
    isPercentage: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "trpm_new",
    label: "New Retailer Profit Margin (%)",
    unit: "%",
    isPercentage: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "tpp",
    label: "Total Profit Pool",
    unit: "£",
    isCurrency: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "tpp_d_abs",
    label: "Profit Pool Change (Abs)",
    unit: "£",
    isCurrency: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "tpp_d_per",
    label: "Profit Pool Change (%)",
    unit: "%",
    isPercentage: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "tpp_new",
    label: "New Profit Pool",
    unit: "£",
    isCurrency: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "tkcpp",
    label: "K-C Profit Pool Share (%)",
    unit: "%",
    isPercentage: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "tkcpp_d_abs",
    label: "K-C Profit Pool Share Change (Abs)",
    unit: "%",
    isPercentage: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "tkcpp_d_per",
    label: "K-C Profit Pool Share Change (%)",
    unit: "%",
    isPercentage: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "tkcpp_new",
    label: "New K-C Profit Pool Share (%)",
    unit: "%",
    isPercentage: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "trpp",
    label: "Retailer Profit Pool Share (%)",
    unit: "%",
    isPercentage: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "trpp_d_abs",
    label: "Retailer Profit Pool Share Change (Abs)",
    unit: "%",
    isPercentage: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "trpp_d_per",
    label: "Retailer Profit Pool Share Change (%)",
    unit: "%",
    isPercentage: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
  {
    key: "trpp_new",
    label: "New Retailer Profit Pool Share (%)",
    unit: "%",
    isPercentage: true,
    category: "profit",
    icon: <AccountBalance />,
    color: "#8B5CF6",
  },
];
