import { Scenario } from "./types";

export const mockScenarios = [
  {
    id: "8d962dea-e8d5-43c0-870d-569885fcf0ad",
    sn: "retr",
    createdBy: "C Sudheeran, Sulabha",
    createdOn: "2025-06-18 08:02:13",
    modifiedOn: null,
    lvl: "OSKU",
    cust: "Tesco",
    cat: "BATH TISSUE",
    yr: "2025",
    mfr: ["K-C"],
    brd: ["ANDREX"],
    subBrd: [
      "Andrex Supreme Quilts",
      "Andrex Skin Kind Washlets",
      "Andrex Puppies",
      "Andrex Classic Clean",
    ],
    ppg: [
      "07 Andrex BT Quilted 4 Roll",
      "09 Andrex Skin Kind Moist TT P1x12",
      "07 Andrex BT Quilted 16 Roll",
      "07 Andrex BT Puppy 24 Roll",
      "07 Andrex Toilet Tissue 4 Roll",
    ],
    osku: [
      "Andrex BT Ultimate Quilts 155sc 4Rx6",
      "Andrex HW Fresh & Soothe 36sc x12",
      "Andrex BT Ult Quilts 155sc 16Rx1 Cube",
      "Andrex BT Family Soft 170sc 24Rx1",
      "Andrex BT Complete Clean 190sc 4Rx6",
    ],
    results_pack: {
      kcTotals: {
        pa: 103,
        pb: 90,
        pd_abs: 13.1,
        pd_per: 14,
        ppk: 1.32,
        ppkd_abs: 0.28,
        ppkd_per: 21.21,
        ra: 10372,
        rb: 9062,
        rd_abs: 1309.99,
        rd_per: 14,
        uppk: 1.6,
        uvpk: 1938,
        vpk: 2021,
        vpkd_abs: -83.11,
        vpkd_per: -4,
        gp_per: 33.3,
      },
      products: [
        {
          brd: "ANDREX",
          cat: "BATH TISSUE",
          cust: "Tesco",
          kpis: [
            {
              pa: 34,
              pb: 33,
              pd_abs: 1.22,
              pd_per: 3.67,
              ppk: 3.03,
              ppkd_abs: 0.65,
              ppkd_per: 21.5,
              pt: "Price Change",
              ra: 3449,
              rb: 3327,
              rd_abs: 122.11,
              rd_per: 3.67,
              uppk: 3.68,
              uvpk: 982,
              vpk: 1096,
              vpkd_abs: -114.89,
              vpkd_per: -10.47,
            },
            {
              pa: 0,
              pb: "-",
              pd_abs: "-",
              pd_per: "-",
              ppk: "-",
              ppkd_abs: "-",
              ppkd_per: "-",
              pt: "Feature",
              ra: 4,
              rb: "-",
              rd_abs: "-",
              rd_per: "-",
              uppk: "-",
              uvpk: 1,
              vpk: "-",
              vpkd_abs: "-",
              vpkd_per: "-",
            },
          ],
          mfr: "K-C",
          osku: "Andrex BT Complete Clean 190sc 4Rx6",
          pid: "Tesco_BATH TISSUE_K-C_Andrex BT Complete Clean 190sc 4Rx6",
          ppg: "07 Andrex Toilet Tissue 4 Roll",
          subBrd: "Andrex Classic Clean",
          total: {
            pa: 34,
            pb: 33,
            pd_abs: 1.26,
            pd_per: 3.79,
            ppk: 3.03,
            ppkd_abs: "-",
            ppkd_per: "-",
            ra: 3453,
            rb: 3327,
            rd_abs: 126.21,
            rd_per: 3.79,
            uppk: "-",
            uvpk: 983,
            vpk: 1096,
            vpkd_abs: -113.78,
            vpkd_per: -10.37,
          },
        },
        {
          brd: "ANDREX",
          cat: "BATH TISSUE",
          cust: "Tesco",
          kpis: [
            {
              pa: 67,
              pb: 57,
              pd_abs: 9.67,
              pd_per: 16.87,
              ppk: 6.2,
              ppkd_abs: 1.33,
              ppkd_per: 21.5,
              pt: "Price Change",
              ra: 6702,
              rb: 5735,
              rd_abs: 967.56,
              rd_per: 16.87,
              uppk: 7.53,
              uvpk: 924,
              vpk: 924,
              vpkd_abs: 0,
              vpkd_per: 0,
            },
            {
              pa: 1,
              pb: "-",
              pd_abs: "-",
              pd_per: "-",
              ppk: "-",
              ppkd_abs: "-",
              ppkd_per: "-",
              pt: "Feature",
              ra: 158,
              rb: "-",
              rd_abs: "-",
              rd_per: "-",
              uppk: "-",
              uvpk: 21,
              vpk: "-",
              vpkd_abs: "-",
              vpkd_per: "-",
            },
          ],
          mfr: "K-C",
          osku: "Andrex BT Family Soft 170sc 24Rx1",
          pid: "Tesco_BATH TISSUE_K-C_Andrex BT Family Soft 170sc 24Rx1",
          ppg: "07 Andrex BT Puppy 24 Roll",
          subBrd: "Andrex Puppies",
          total: {
            pa: 68,
            pb: 57,
            pd_abs: 11.26,
            pd_per: 19.63,
            ppk: 6.2,
            ppkd_abs: "-",
            ppkd_per: "-",
            ra: 6861,
            rb: 5735,
            rd_abs: 1126.08,
            rd_per: 19.63,
            uppk: "-",
            uvpk: 945,
            vpk: 924,
            vpkd_abs: 21.03,
            vpkd_per: 2.27,
          },
        },
        {
          brd: "ANDREX",
          cat: "BATH TISSUE",
          cust: "Tesco",
          kpis: [
            {
              pa: 0,
              pb: "-",
              pd_abs: "-",
              pd_per: "-",
              ppk: "-",
              ppkd_abs: "-",
              ppkd_per: "-",
              pt: "Feature",
              ra: 47,
              rb: "-",
              rd_abs: "-",
              rd_per: "-",
              uppk: "-",
              uvpk: 5,
              vpk: "-",
              vpkd_abs: "-",
              vpkd_per: "-",
            },
          ],
          mfr: "K-C",
          osku: "Andrex BT Ult Quilts 155sc 16Rx1 Cube",
          pid: "Tesco_BATH TISSUE_K-C_Andrex BT Ult Quilts 155sc 16Rx1 Cube",
          ppg: "07 Andrex BT Quilted 16 Roll",
          subBrd: "Andrex Supreme Quilts",
          total: {
            pa: 52,
            pb: 51,
            pd_abs: 0.47,
            pd_per: 0.93,
            ppk: 9.1,
            ppkd_abs: "-",
            ppkd_per: "-",
            ra: 5200,
            rb: 5152,
            rd_abs: 47.95,
            rd_per: 0.93,
            uppk: "-",
            uvpk: 571,
            vpk: 566,
            vpkd_abs: 5.26,
            vpkd_per: 0.93,
          },
        },
        {
          brd: "ANDREX",
          cat: "BATH TISSUE",
          cust: "Tesco",
          kpis: [
            {
              pa: 0,
              pb: "-",
              pd_abs: "-",
              pd_per: "-",
              ppk: "-",
              ppkd_abs: "-",
              ppkd_per: "-",
              pt: "Feature",
              ra: 9,
              rb: "-",
              rd_abs: "-",
              rd_per: "-",
              uppk: "-",
              uvpk: 4,
              vpk: "-",
              vpkd_abs: "-",
              vpkd_per: "-",
            },
          ],
          mfr: "K-C",
          osku: "Andrex BT Ultimate Quilts 155sc 4Rx6",
          pid: "Tesco_BATH TISSUE_K-C_Andrex BT Ultimate Quilts 155sc 4Rx6",
          ppg: "07 Andrex BT Quilted 4 Roll",
          subBrd: "Andrex Supreme Quilts",
          total: {
            pa: 17,
            pb: 17,
            pd_abs: 0.09,
            pd_per: 0.53,
            ppk: 2.29,
            ppkd_abs: "-",
            ppkd_per: "-",
            ra: 1767,
            rb: 1757,
            rd_abs: 9.47,
            rd_per: 0.53,
            uppk: "-",
            uvpk: 769,
            vpk: 765,
            vpkd_abs: 4.12,
            vpkd_per: 0.53,
          },
        },
        {
          brd: "ANDREX",
          cat: "BATH TISSUE",
          cust: "Tesco",
          kpis: [
            {
              pa: 0,
              pb: "-",
              pd_abs: "-",
              pd_per: "-",
              ppk: "-",
              ppkd_abs: "-",
              ppkd_per: "-",
              pt: "Feature",
              ra: 0,
              rb: "-",
              rd_abs: "-",
              rd_per: "-",
              uppk: "-",
              uvpk: 0,
              vpk: "-",
              vpkd_abs: "-",
              vpkd_per: "-",
            },
          ],
          mfr: "K-C",
          osku: "Andrex HW Fresh & Soothe 36sc x12",
          pid: "Tesco_BATH TISSUE_K-C_Andrex HW Fresh & Soothe 36sc x12",
          ppg: "09 Andrex Skin Kind Moist TT P1x12",
          subBrd: "Andrex Skin Kind Washlets",
          total: {
            pa: 0,
            pb: 0,
            pd_abs: 0,
            pd_per: 0.29,
            ppk: 1.17,
            ppkd_abs: "-",
            ppkd_per: "-",
            ra: 92,
            rb: 91,
            rd_abs: 0.27,
            rd_per: 0.29,
            uppk: "-",
            uvpk: 78,
            vpk: 78,
            vpkd_abs: 0.23,
            vpkd_per: 0.29,
          },
        },
        {
          brd: "ALL OTHER",
          cat: "BATH TISSUE",
          cust: "Tesco",
          kpis: [
            {
              pa: 0,
              pb: 0,
              pd_abs: 0,
              pd_per: 0,
              ppk: 2.54,
              ppkd_abs: 0,
              ppkd_per: 0,
              pt: "No Promo",
              ra: 61,
              rb: 61,
              rd_abs: 0,
              rd_per: 0,
              uppk: 2.54,
              uvpk: 0,
              vpk: 0,
              vpkd_abs: 0,
              vpkd_per: 0,
            },
          ],
          mfr: "ALL OTHER",
          osku: "Dry Toilet Tissue Tesco ALL OTHER 4",
          pid: "Tesco_BATH TISSUE_ALL OTHER_Dry Toilet Tissue Tesco ALL OTHER 4",
          ppg: "Dry Toilet Tissue Tesco ALL OTHER 4",
          subBrd: "All Other",
          total: {
            pa: 0,
            pb: 0,
            pd_abs: 0,
            pd_per: 0,
            ppk: 2.54,
            ppkd_abs: 0,
            ppkd_per: 0,
            ra: 61,
            rb: 61,
            rd_abs: 0,
            rd_per: 0,
            uppk: 2.54,
            uvpk: 0,
            vpk: 0,
            vpkd_abs: 0,
            vpkd_per: 0,
          },
        },
        {
          brd: "ALL OTHER",
          cat: "BATH TISSUE",
          cust: "Tesco",
          kpis: [
            {
              pa: 0,
              pb: 0,
              pd_abs: 0,
              pd_per: 0,
              ppk: 5.5,
              ppkd_abs: 0,
              ppkd_per: 0,
              pt: "No Promo",
              ra: 28286,
              rb: 28286,
              rd_abs: 0,
              rd_per: 0,
              uppk: 5.5,
              uvpk: 111,
              vpk: 111,
              vpkd_abs: 0,
              vpkd_per: 0,
            },
          ],
          mfr: "ALL OTHER",
          osku: "Dry Toilet Tissue Tesco ALL OTHER 24",
          pid: "Tesco_BATH TISSUE_ALL OTHER_Dry Toilet Tissue Tesco ALL OTHER 24",
          ppg: "Dry Toilet Tissue Tesco ALL OTHER 24",
          subBrd: "All Other",
          total: {
            pa: 0,
            pb: 0,
            pd_abs: 0,
            pd_per: 0,
            ppk: 5.5,
            ppkd_abs: 0,
            ppkd_per: 0,
            ra: 28286,
            rb: 28286,
            rd_abs: 0,
            rd_per: 0,
            uppk: 5.5,
            uvpk: 111,
            vpk: 111,
            vpkd_abs: 0,
            vpkd_per: 0,
          },
        },
        {
          brd: "CUSHELLE",
          cat: "BATH TISSUE",
          cust: "Tesco",
          kpis: [
            {
              pa: 0,
              pb: 0,
              pd_abs: 0,
              pd_per: 0,
              ppk: 6.85,
              ppkd_abs: 0,
              ppkd_per: 0,
              pt: "No Promo",
              ra: 7547,
              rb: 7547,
              rd_abs: 0,
              rd_per: 0,
              uppk: 6.85,
              uvpk: 23,
              vpk: 23,
              vpkd_abs: 0,
              vpkd_per: 0,
            },
          ],
          mfr: "ESSITY",
          osku: "CUSHELLE QUILTED 9",
          pid: "Tesco_BATH TISSUE_ESSITY_CUSHELLE QUILTED 9",
          ppg: "CUSHELLE QUILTED 9",
          subBrd: "Cushelle Quilted",
          total: {
            pa: 0,
            pb: 0,
            pd_abs: 0,
            pd_per: 0,
            ppk: 6.85,
            ppkd_abs: 0,
            ppkd_per: 0,
            ra: 7547,
            rb: 7547,
            rd_abs: 0,
            rd_per: 0,
            uppk: 6.85,
            uvpk: 23,
            vpk: 23,
            vpkd_abs: 0,
            vpkd_per: 0,
          },
        },
      ],
      totals: {
        pa: 103,
        pb: 90,
        pd_abs: 13.1,
        pd_per: 14,
        ppk: 2.41,
        ppkd_abs: 0.2,
        ppkd_per: 8.3,
        ra: 46268,
        rb: 44958,
        rd_abs: 1309.99,
        rd_per: 3,
        uppk: 2.61,
        uvpk: 2075,
        vpk: 2158,
        vpkd_abs: -83.11,
        vpkd_per: -4,
      },
    },
    results_su: {
      kcTotals: {
        gp_per: 25.5,
        pa: 0,
        pb: 0,
        pd_abs: 0,
        pd_per: null,
        ppk: 0.41,
        ppkd_abs: 0.09,
        ppkd_per: 21.95,
        ra: 2,
        rb: 2,
        rd_abs: 0,
        rd_per: 0,
        uppk: 0.5,
        uvpk: 0,
        vpk: 0,
        vpkd_abs: 0,
        vpkd_per: null,
      },
    },
  },
  {
    id: "136ac580-2ecd-4837-8310-4f6e037f498a",
    sn: "qwqw",
    createdBy: "C Sudheeran, Sulabha",
    createdOn: "2025-06-18 08:57:15",
    modifiedOn: null,
    lvl: "OSKU",
    cust: "Tesco",
    cat: "BATH TISSUE",
    yr: "2025",
    mfr: ["K-C"],
    brd: ["ANDREX"],
    subBrd: [
      "Andrex Supreme Quilts",
      "Andrex Skin Kind Washlets",
      "Andrex Puppies",
      "Andrex Classic Clean",
    ],
    ppg: [
      "07 Andrex BT Quilted 4 Roll",
      "09 Andrex Skin Kind Moist TT P1x12",
      "07 Andrex BT Quilted 16 Roll",
      "07 Andrex BT Puppy 24 Roll",
      "07 Andrex Toilet Tissue 4 Roll",
    ],
    osku: [
      "Andrex BT Ultimate Quilts 155sc 4Rx6",
      "Andrex HW Fresh & Soothe 36sc x12",
      "Andrex BT Ult Quilts 155sc 16Rx1 Cube",
      "Andrex BT Family Soft 170sc 24Rx1",
      "Andrex BT Complete Clean 190sc 4Rx6",
    ],
    results_pack: {
      kcTotals: {
        pa: 105,
        pb: 90,
        pd_abs: 15.3,
        pd_per: 17,
        ppk: 1.32,
        ppkd_abs: 0.39,
        ppkd_per: 29.55,
        ra: 10593,
        rb: 9062,
        rd_abs: 1530.89,
        rd_per: 17,
        uppk: 1.71,
        uvpk: 1883,
        vpk: 2021,
        vpkd_abs: -138.49,
        vpkd_per: -7,
        gp_per: 35.2,
      },
    },
    results_su: {
      kcTotals: {
        gp_per: 28.7,
        pa: 0,
        pb: 0,
        pd_abs: 0,
        pd_per: null,
        ppk: 0.41,
        ppkd_abs: 0.13,
        ppkd_per: 31.7,
        ra: 3,
        rb: 2,
        rd_abs: 1,
        rd_per: 50,
        uppk: 0.54,
        uvpk: 0,
        vpk: 0,
        vpkd_abs: 0,
        vpkd_per: null,
      },
    },
  },
];
