const mockData = [
  {
    mfr: "K-C",
    cust: "Morrisons Group",
    cat: "BATH TISSUE",
    brd: "ANDREX",
    subBrd: "Andrex Puppies",
    pid: "Morrisons Group_BATH TISSUE_K-C_07 Andrex Puppy 4 roll",
    ppg: "07 Andrex Puppy 4 roll",
    section: "base",
    priceperpiece: 0.6,
    priceperpack: 12,
    "AvgBaseVolume(Packs)": 90,
    "AvgBaseVolume(Piece)": 180,
    PromoPeriod: "2023-12-01 to 2023-12-31",
    PromoPrice: 9,
    RetailersMargin: 18,
    "predicted volume per week": 110,
    "uplifts vs base": 15,
  },
  {
    mfr: "K-C",
    cust: "Ocado",
    cat: "BATH TISSUE",
    brd: "ANDREX",
    subBrd: "Andrex Supreme Quilts",
    pid: "Ocado_BATH TISSUE_K-C_07 Andrex BT Quilted 4 Roll",
    ppg: "07 Andrex BT Quilted 4 Roll",
    section: "base",
    priceperpiece: 0.6,
    priceperpack: 12,
    "AvgBaseVolume(Packs)": 90,
    "AvgBaseVolume(Piece)": 180,
    PromoPeriod: "2023-12-01 to 2023-12-31",
    PromoPrice: 9,
    RetailersMargin: 18,
    "predicted volume per week": 110,
    "uplifts vs base": 15,
  },
  {
    mfr: "K-C",
    cust: "Morrisons Group",
    cat: "BATH TISSUE",
    brd: "ANDREX",
    subBrd: "Andrex Classic Clean",
    pid: "Morrisons Group_BATH TISSUE_K-C_07 Andrex Toilet Tissue 12 Roll",
    ppg: "07 Andrex Toilet Tissue 12 Roll",
    section: "base",
    priceperpiece: 0.6,
    priceperpack: 12,
    "AvgBaseVolume(Packs)": 90,
    "AvgBaseVolume(Piece)": 180,
    PromoPeriod: "2023-12-01 to 2023-12-31",
    PromoPrice: 9,
    RetailersMargin: 18,
    "predicted volume per week": 110,
    "uplifts vs base": 15,
  },

  {
    mfr: "K-C",
    cust: "Asda",
    cat: "BATH TISSUE",
    brd: "ANDREX",
    subBrd: "Andrex Classic Clean",
    pid: "Asda_BATH TISSUE_K-C_07 Andrex Toilet Tissue 12 Roll Mega",
    ppg: "07 Andrex Toilet Tissue 12 Roll Mega",
    section: "base",
    priceperpiece: 0.5,
    priceperpack: 10,
    "AvgBaseVolume(Packs)": 100,
    "AvgBaseVolume(Piece)": 200,
    PromoPeriod: "2023-11-01 to 2023-11-30",
    PromoPrice: 8,
    RetailersMargin: 15,
    "predicted volume per week": 120,
    "uplifts vs base": 20,
  },
  {
    mfr: "K-C",
    cust: "Ocado",
    cat: "BATH TISSUE",
    brd: "ANDREX",
    subBrd: "Andrex Skin Kind Washlets",
    pid: "Ocado_BATH TISSUE_K-C_09 Andrex Skin Kind Moist TT P4x3",
    ppg: "09 Andrex Skin Kind Moist TT P4x3",
    section: "base",
    priceperpiece: 0.4,
    priceperpack: 8,
    "AvgBaseVolume(Packs)": 80,
    "AvgBaseVolume(Piece)": 160,
    PromoPeriod: "2023-10-01 to 2023-10-31",
    PromoPrice: 7,
    RetailersMargin: 12,
    "predicted volume per week": 100,
    "uplifts vs base": 10,
  },
  {
    mfr: "K-C",
    cust: "Asda",
    cat: "BATH TISSUE",
    brd: "ANDREX",
    subBrd: "Andrex Moist",
    pid: "Asda_BATH TISSUE_K-C_09 Andrex Pure Care Moist TT P1x12",
    ppg: "09 Andrex Pure Care Moist TT P1x12",
    section: "base",
    priceperpiece: 0.5,
    priceperpack: 10,
    "AvgBaseVolume(Packs)": 100,
    "AvgBaseVolume(Piece)": 200,
    PromoPeriod: "2023-11-01 to 2023-11-30",
    PromoPrice: 8,
    RetailersMargin: 15,
    "predicted volume per week": 120,
    "uplifts vs base": 20,
  },
  {
    mfr: "K-C",
    cust: "Total Co-ops",
    cat: "BATH TISSUE",
    brd: "ANDREX",
    subBrd: "Andrex Classic Clean Washlets",
    pid: "Total Co-ops_BATH TISSUE_K-C_09 Andrex Moist Refill x 12",
    ppg: "09 Andrex Moist Refill x 12",
    section: "base",
    priceperpiece: 0.6,
    priceperpack: 12,
    "AvgBaseVolume(Packs)": 90,
    "AvgBaseVolume(Piece)": 180,
    PromoPeriod: "2023-12-01 to 2023-12-31",
    PromoPrice: 9,
    RetailersMargin: 18,
    "predicted volume per week": 110,
    "uplifts vs base": 15,
  },
  {
    mfr: "P&G",
    cust: "Ocado",
    cat: "BABY WIPES",
    brd: "PAMPERS",
    subBrd: "Pampers Sensitive",
    pid: "Ocado_BABY WIPES_P&G_PAMPERS SENSITIVE 4",
    ppg: "PAMPERS SENSITIVE 4",
    section: "base",
    priceperpiece: 0.4,
    priceperpack: 8,
    "AvgBaseVolume(Packs)": 80,
    "AvgBaseVolume(Piece)": 160,
    PromoPeriod: "2023-10-01 to 2023-10-31",
    PromoPrice: 7,
    RetailersMargin: 12,
    "predicted volume per week": 100,
    "uplifts vs base": 10,
  },
];

export default mockData;
