const mockData = [
  {
    mfr: "ALL OTHER",
    cust: "Ocado",
    cat: "DIAPERS & PANTS",
    brd: "ALL OTHER",
    subBrd: "All Other",
    pid: "Ocado_DIAPERS & PANTS_ALL OTHER_Diaper Pants (Closed) Ocado ALL OTHER 14",
    ppg: "Diaper Pants (Closed) Ocado ALL OTHER 14",
    section: "base",
    priceperpiece: 0.5,
    priceperpack: 10,
    "AvgBaseVolume(Packs)": 100,
    "AvgBaseVolume(Piece)": 200,
    PromoPeriod: "2023-11-01 to 2023-11-30",
    PromoPrice: 8,
    RetailersMargin: 15,
    "predicted volume per week": 120,
    "uplifts vs base": 20,
  },
  {
    mfr: "K-C",
    cust: "Tesco Superstores",
    cat: "DIAPERS & PANTS",
    brd: "HUGGIES",
    subBrd: "Huggies Dry Nites",
    pid: "Tesco Superstores_DIAPERS & PANTS_K-C_09 Hg Drynites Convenience x 3",
    ppg: "09 Hg Drynites Convenience x 3",
    section: "base",
    priceperpiece: 0.6,
    priceperpack: 12,
    "AvgBaseVolume(Packs)": 90,
    "AvgBaseVolume(Piece)": 180,
    PromoPeriod: "2023-12-01 to 2023-12-31",
    PromoPrice: 9,
    RetailersMargin: 18,
    "predicted volume per week": 110,
    "uplifts vs base": 15,
  },
  {
    mfr: "P&G",
    cust: "Ocado",
    cat: "DIAPERS & PANTS",
    brd: "PAMPERS",
    subBrd: "Baby Dry",
    pid: "Ocado_DIAPERS & PANTS_P&G_Baby Diapers (Open) BABY DRY 84",
    ppg: "Baby Diapers (Open) BABY DRY 84",
    section: "base",
    priceperpiece: 0.4,
    priceperpack: 8,
    "AvgBaseVolume(Packs)": 80,
    "AvgBaseVolume(Piece)": 160,
    PromoPeriod: "2023-10-01 to 2023-10-31",
    PromoPrice: 7,
    RetailersMargin: 12,
    "predicted volume per week": 100,
    "uplifts vs base": 10,
  },
  {
    mfr: "ALL OTHER",
    cust: "Tesco",
    cat: "DIAPERS & PANTS",
    brd: "ALL OTHER",
    subBrd: "Rascal + Friends",
    pid: "Tesco_DIAPERS & PANTS_ALL OTHER_Baby Diapers (Open) RASCAL + FRIENDS 32",
    ppg: "Baby Diapers (Open) RASCAL + FRIENDS 32",
    section: "base",
    priceperpiece: 0.5,
    priceperpack: 10,
    "AvgBaseVolume(Packs)": 100,
    "AvgBaseVolume(Piece)": 200,
    PromoPeriod: "2023-11-01 to 2023-11-30",
    PromoPrice: 8,
    RetailersMargin: 15,
    "predicted volume per week": 120,
    "uplifts vs base": 20,
  },
  {
    mfr: "ALL OTHER",
    cust: "National",
    cat: "FACIAL TISSUE",
    brd: "SANI HANDS",
    subBrd: "Sani Hands",
    pid: "National_FACIAL TISSUE_ALL OTHER_Wet Wipes National SANI HANDS 1",
    ppg: "Wet Wipes National SANI HANDS 1",
    section: "base",
    priceperpiece: 0.6,
    priceperpack: 12,
    "AvgBaseVolume(Packs)": 90,
    "AvgBaseVolume(Piece)": 180,
    PromoPeriod: "2023-12-01 to 2023-12-31",
    PromoPrice: 9,
    RetailersMargin: 18,
    "predicted volume per week": 110,
    "uplifts vs base": 15,
  },
  {
    mfr: "ALL OTHER",
    cust: "Tesco",
    cat: "DIAPERS & PANTS",
    brd: "ALL OTHER",
    subBrd: "All Other",
    pid: "Tesco_DIAPERS & PANTS_ALL OTHER_Baby Diapers (Open) Tesco ALL OTHER 42",
    ppg: "Baby Diapers (Open) Tesco ALL OTHER 42",
    section: "base",
    priceperpiece: 0.4,
    priceperpack: 8,
    "AvgBaseVolume(Packs)": 80,
    "AvgBaseVolume(Piece)": 160,
    PromoPeriod: "2023-10-01 to 2023-10-31",
    PromoPrice: 7,
    RetailersMargin: 12,
    "predicted volume per week": 100,
    "uplifts vs base": 10,
  },
  {
    mfr: "ALL OTHER",
    cust: "Waitrose",
    cat: "FACIAL TISSUE",
    brd: "SANI HANDS",
    subBrd: "Sani Hands",
    pid: "Waitrose_FACIAL TISSUE_ALL OTHER_Wet Wipes Waitrose SANI HANDS 1",
    ppg: "Wet Wipes Waitrose SANI HANDS 1",
    section: "base",
    priceperpiece: 0.5,
    priceperpack: 10,
    "AvgBaseVolume(Packs)": 100,
    "AvgBaseVolume(Piece)": 200,
    PromoPeriod: "2023-11-01 to 2023-11-30",
    PromoPrice: 8,
    RetailersMargin: 15,
    "predicted volume per week": 120,
    "uplifts vs base": 20,
  },
  {
    mfr: "K-C",
    cust: "Morrisons Group",
    cat: "BATH TISSUE",
    brd: "ANDREX",
    subBrd: "Andrex Puppies",
    pid: "Morrisons Group_BATH TISSUE_K-C_07 Andrex Puppy 4 roll",
    ppg: "07 Andrex Puppy 4 roll",
    section: "base",
    priceperpiece: 0.6,
    priceperpack: 12,
    "AvgBaseVolume(Packs)": 90,
    "AvgBaseVolume(Piece)": 180,
    PromoPeriod: "2023-12-01 to 2023-12-31",
    PromoPrice: 9,
    RetailersMargin: 18,
    "predicted volume per week": 110,
    "uplifts vs base": 15,
  },
  {
    mfr: "P&G",
    cust: "Waitrose",
    cat: "BABY WIPES",
    brd: "PAMPERS",
    subBrd: "Sensitive",
    pid: "Waitrose_BABY WIPES_P&G_SENSITIVE 4",
    ppg: "SENSITIVE 4",
    section: "base",
    priceperpiece: 0.4,
    priceperpack: 8,
    "AvgBaseVolume(Packs)": 80,
    "AvgBaseVolume(Piece)": 160,
    PromoPeriod: "2023-10-01 to 2023-10-31",
    PromoPrice: 7,
    RetailersMargin: 12,
    "predicted volume per week": 100,
    "uplifts vs base": 10,
  },
  {
    mfr: "SOFIDEL",
    cust: "National",
    cat: "BATH TISSUE",
    brd: "NICKY",
    subBrd: "Nicky Quilted",
    pid: "National_BATH TISSUE_SOFIDEL_Nicky Quilted 9",
    ppg: "Nicky Quilted 9",
    section: "base",
    priceperpiece: 0.5,
    priceperpack: 10,
    "AvgBaseVolume(Packs)": 100,
    "AvgBaseVolume(Piece)": 200,
    PromoPeriod: "2023-11-01 to 2023-11-30",
    PromoPrice: 8,
    RetailersMargin: 15,
    "predicted volume per week": 120,
    "uplifts vs base": 20,
  },
  {
    mfr: "P&G",
    cust: "Waitrose",
    cat: "DIAPERS & PANTS",
    brd: "PAMPERS",
    subBrd: "Premium Protection",
    pid: "Waitrose_DIAPERS & PANTS_P&G_Baby Diapers (Open) PREMIUM PROTECTION 28",
    ppg: "Baby Diapers (Open) PREMIUM PROTECTION 28",
    section: "base",
    priceperpiece: 0.6,
    priceperpack: 12,
    "AvgBaseVolume(Packs)": 90,
    "AvgBaseVolume(Piece)": 180,
    PromoPeriod: "2023-12-01 to 2023-12-31",
    PromoPrice: 9,
    RetailersMargin: 18,
    "predicted volume per week": 110,
    "uplifts vs base": 15,
  },
  {
    mfr: "P&G",
    cust: "Sainsbury Superstores",
    cat: "DIAPERS & PANTS",
    brd: "PAMPERS",
    subBrd: "Baby Dry Pants",
    pid: "Sainsbury Superstores_DIAPERS & PANTS_P&G_Diaper Pants (Closed) BABY DRY PANTS 50",
    ppg: "Diaper Pants (Closed) BABY DRY PANTS 50",
    section: "base",
    priceperpiece: 0.4,
    priceperpack: 8,
    "AvgBaseVolume(Packs)": 80,
    "AvgBaseVolume(Piece)": 160,
    PromoPeriod: "2023-10-01 to 2023-10-31",
    PromoPrice: 7,
    RetailersMargin: 12,
    "predicted volume per week": 100,
    "uplifts vs base": 10,
  },
  {
    mfr: "ALL OTHER",
    cust: "National",
    cat: "DIAPERS & PANTS",
    brd: "ALL OTHER",
    subBrd: "All Other",
    pid: "National_DIAPERS & PANTS_ALL OTHER_Baby Diapers (Open) National ALL OTHER 20",
    ppg: "Baby Diapers (Open) National ALL OTHER 20",
    section: "base",
    priceperpiece: 0.5,
    priceperpack: 10,
    "AvgBaseVolume(Packs)": 100,
    "AvgBaseVolume(Piece)": 200,
    PromoPeriod: "2023-11-01 to 2023-11-30",
    PromoPrice: 8,
    RetailersMargin: 15,
    "predicted volume per week": 120,
    "uplifts vs base": 20,
  },
  {
    mfr: "PRIVATE LABEL",
    cust: "Waitrose",
    cat: "FACIAL TISSUE",
    brd: "PRIVATE LABEL",
    subBrd: "Pl All Other",
    pid: "Waitrose_FACIAL TISSUE_PRIVATE LABEL_Boxes Waitrose PL All Other 1",
    ppg: "Boxes Waitrose PL All Other 1",
    section: "base",
    priceperpiece: 0.6,
    priceperpack: 12,
    "AvgBaseVolume(Packs)": 90,
    "AvgBaseVolume(Piece)": 180,
    PromoPeriod: "2023-12-01 to 2023-12-31",
    PromoPrice: 9,
    RetailersMargin: 18,
    "predicted volume per week": 110,
    "uplifts vs base": 15,
  },
  {
    mfr: "SOFIDEL",
    cust: "Sainsbury",
    cat: "BATH TISSUE",
    brd: "NICKY",
    subBrd: "Nicky Supreme",
    pid: "Sainsbury_BATH TISSUE_SOFIDEL_Nicky Supreme 4",
    ppg: "Nicky Supreme 4",
    section: "base",
    priceperpiece: 0.4,
    priceperpack: 8,
    "AvgBaseVolume(Packs)": 80,
    "AvgBaseVolume(Piece)": 160,
    PromoPeriod: "2023-10-01 to 2023-10-31",
    PromoPrice: 7,
    RetailersMargin: 12,
    "predicted volume per week": 100,
    "uplifts vs base": 10,
  },
  {
    mfr: "P&G",
    cust: "Sainsbury Superstores",
    cat: "DIAPERS & PANTS",
    brd: "PAMPERS",
    subBrd: "Nappy Pants",
    pid: "Sainsbury Superstores_DIAPERS & PANTS_P&G_Diaper Pants (Closed) NAPPY PANTS 21",
    ppg: "Diaper Pants (Closed) NAPPY PANTS 21",
    section: "base",
    priceperpiece: 0.5,
    priceperpack: 10,
    "AvgBaseVolume(Packs)": 100,
    "AvgBaseVolume(Piece)": 200,
    PromoPeriod: "2023-11-01 to 2023-11-30",
    PromoPrice: 8,
    RetailersMargin: 15,
    "predicted volume per week": 120,
    "uplifts vs base": 20,
  },
  {
    mfr: "ALL OTHER",
    cust: "Ocado",
    cat: "DIAPERS & PANTS",
    brd: "ALL OTHER",
    subBrd: "Naty Nature Baby Care",
    pid: "Ocado_DIAPERS & PANTS_ALL OTHER_Baby Diapers (Open) Naty Nature Baby Care 44",
    ppg: "Baby Diapers (Open) Naty Nature Baby Care 44",
    section: "base",
    priceperpiece: 0.6,
    priceperpack: 12,
    "AvgBaseVolume(Packs)": 90,
    "AvgBaseVolume(Piece)": 180,
    PromoPeriod: "2023-12-01 to 2023-12-31",
    PromoPrice: 9,
    RetailersMargin: 18,
    "predicted volume per week": 110,
    "uplifts vs base": 15,
  },
  {
    mfr: "ALL OTHER",
    cust: "Sainsbury Superstores",
    cat: "FACIAL TISSUE",
    brd: "WET ONES",
    subBrd: "Wet Ones Be Cute",
    pid: "Sainsbury Superstores_FACIAL TISSUE_ALL OTHER_Wet Wipes Sainsbury Superstores WET ONES BE CUTE 1",
    ppg: "Wet Wipes Sainsbury Superstores WET ONES BE CUTE 1",
    section: "base",
    priceperpiece: 0.4,
    priceperpack: 8,
    "AvgBaseVolume(Packs)": 80,
    "AvgBaseVolume(Piece)": 160,
    PromoPeriod: "2023-10-01 to 2023-10-31",
    PromoPrice: 7,
    RetailersMargin: 12,
    "predicted volume per week": 100,
    "uplifts vs base": 10,
  },
  {
    mfr: "PRIVATE LABEL",
    cust: "National",
    cat: "FACIAL TISSUE",
    brd: "PRIVATE LABEL",
    subBrd: "Private Label",
    pid: "National_FACIAL TISSUE_PRIVATE LABEL_Pocket National PRIVATE LABEL 10",
    ppg: "Pocket National PRIVATE LABEL 10",
    section: "base",
    priceperpiece: 0.5,
    priceperpack: 10,
    "AvgBaseVolume(Packs)": 100,
    "AvgBaseVolume(Piece)": 200,
    PromoPeriod: "2023-11-01 to 2023-11-30",
    PromoPrice: 8,
    RetailersMargin: 15,
    "predicted volume per week": 120,
    "uplifts vs base": 20,
  },
  {
    mfr: "P&G",
    cust: "Sainsbury Superstores",
    cat: "DIAPERS & PANTS",
    brd: "PAMPERS",
    subBrd: "Pampers Baby Dry",
    pid: "Sainsbury Superstores_DIAPERS & PANTS_P&G_Baby Diapers (Open) PAMPERS BABY DRY 39",
    ppg: "Baby Diapers (Open) PAMPERS BABY DRY 39",
    section: "base",
    priceperpiece: 0.6,
    priceperpack: 12,
    "AvgBaseVolume(Packs)": 90,
    "AvgBaseVolume(Piece)": 180,
    PromoPeriod: "2023-12-01 to 2023-12-31",
    PromoPrice: 9,
    RetailersMargin: 18,
    "predicted volume per week": 110,
    "uplifts vs base": 15,
  },
  {
    mfr: "P&G",
    cust: "Sainsbury Superstores",
    cat: "DIAPERS & PANTS",
    brd: "PAMPERS",
    subBrd: "Premium Protection New Baby",
    pid: "Sainsbury Superstores_DIAPERS & PANTS_P&G_Baby Diapers (Open) PREMIUM PROTECTION NEW BABY 44",
    ppg: "Baby Diapers (Open) PREMIUM PROTECTION NEW BABY 44",
    section: "base",
    priceperpiece: 0.4,
    priceperpack: 8,
    "AvgBaseVolume(Packs)": 80,
    "AvgBaseVolume(Piece)": 160,
    PromoPeriod: "2023-10-01 to 2023-10-31",
    PromoPrice: 7,
    RetailersMargin: 12,
    "predicted volume per week": 100,
    "uplifts vs base": 10,
  },
  {
    mfr: "P&G",
    cust: "Tesco Extra",
    cat: "DIAPERS & PANTS",
    brd: "PAMPERS",
    subBrd: "Splashers",
    pid: "Tesco Extra_DIAPERS & PANTS_P&G_Swimming Pants SPLASHERS 12",
    ppg: "Swimming Pants SPLASHERS 12",
    section: "base",
    priceperpiece: 0.5,
    priceperpack: 10,
    "AvgBaseVolume(Packs)": 100,
    "AvgBaseVolume(Piece)": 200,
    PromoPeriod: "2023-11-01 to 2023-11-30",
    PromoPrice: 8,
    RetailersMargin: 15,
    "predicted volume per week": 120,
    "uplifts vs base": 20,
  },
  {
    mfr: "P&G",
    cust: "Tesco Superstores",
    cat: "DIAPERS & PANTS",
    brd: "PAMPERS",
    subBrd: "Pampers Baby Dry",
    pid: "Tesco Superstores_DIAPERS & PANTS_P&G_Diaper Pants (Closed) PAMPERS BABY DRY 22",
    ppg: "Diaper Pants (Closed) PAMPERS BABY DRY 22",
    section: "base",
    priceperpiece: 0.6,
    priceperpack: 12,
    "AvgBaseVolume(Packs)": 90,
    "AvgBaseVolume(Piece)": 180,
    PromoPeriod: "2023-12-01 to 2023-12-31",
    PromoPrice: 9,
    RetailersMargin: 18,
    "predicted volume per week": 110,
    "uplifts vs base": 15,
  },
  {
    mfr: "P&G",
    cust: "Waitrose",
    cat: "DIAPERS & PANTS",
    brd: "PAMPERS",
    subBrd: "Pampers Baby Dry",
    pid: "Waitrose_DIAPERS & PANTS_P&G_Baby Diapers (Open) PAMPERS BABY DRY 44",
    ppg: "Baby Diapers (Open) PAMPERS BABY DRY 44",
    section: "base",
    priceperpiece: 0.4,
    priceperpack: 8,
    "AvgBaseVolume(Packs)": 80,
    "AvgBaseVolume(Piece)": 160,
    PromoPeriod: "2023-10-01 to 2023-10-31",
    PromoPrice: 7,
    RetailersMargin: 12,
    "predicted volume per week": 100,
    "uplifts vs base": 10,
  },
  {
    mfr: "ALL OTHER",
    cust: "Ocado",
    cat: "BABY WIPES",
    brd: "ALL OTHER",
    subBrd: "All Other",
    pid: "Ocado_BABY WIPES_ALL OTHER_Baby Wipes Ocado ALL OTHER 6",
    ppg: "Baby Wipes Ocado ALL OTHER 6",
    section: "base",
    priceperpiece: 0.5,
    priceperpack: 10,
    "AvgBaseVolume(Packs)": 100,
    "AvgBaseVolume(Piece)": 200,
    PromoPeriod: "2023-11-01 to 2023-11-30",
    PromoPrice: 8,
    RetailersMargin: 15,
    "predicted volume per week": 120,
    "uplifts vs base": 20,
  },
  {
    mfr: "K-C",
    cust: "Asda",
    cat: "BATH TISSUE",
    brd: "ANDREX",
    subBrd: "Andrex Classic Clean",
    pid: "Asda_BATH TISSUE_K-C_07 Andrex Toilet Tissue 4 Roll",
    ppg: "07 Andrex Toilet Tissue 4 Roll",
    section: "base",
    priceperpiece: 0.6,
    priceperpack: 12,
    "AvgBaseVolume(Packs)": 90,
    "AvgBaseVolume(Piece)": 180,
    PromoPeriod: "2023-12-01 to 2023-12-31",
    PromoPrice: 9,
    RetailersMargin: 18,
    "predicted volume per week": 110,
    "uplifts vs base": 15,
  },
  {
    mfr: "P&G",
    cust: "Tesco",
    cat: "DIAPERS & PANTS",
    brd: "PAMPERS",
    subBrd: "Pampers Baby Dry",
    pid: "Tesco_DIAPERS & PANTS_P&G_Baby Diapers (Open) PAMPERS BABY DRY 76",
    ppg: "Baby Diapers (Open) PAMPERS BABY DRY 76",
    section: "base",
    priceperpiece: 0.4,
    priceperpack: 8,
    "AvgBaseVolume(Packs)": 80,
    "AvgBaseVolume(Piece)": 160,
    PromoPeriod: "2023-10-01 to 2023-10-31",
    PromoPrice: 7,
    RetailersMargin: 12,
    "predicted volume per week": 100,
    "uplifts vs base": 10,
  },
  {
    mfr: "SOFIDEL",
    cust: "Morrisons Group",
    cat: "BATH TISSUE",
    brd: "REGINA",
    subBrd: "Regina",
    pid: "Morrisons Group_BATH TISSUE_SOFIDEL_REGINA 4",
    ppg: "REGINA 4",
    section: "base",
    priceperpiece: 0.5,
    priceperpack: 10,
    "AvgBaseVolume(Packs)": 100,
    "AvgBaseVolume(Piece)": 200,
    PromoPeriod: "2023-11-01 to 2023-11-30",
    PromoPrice: 8,
    RetailersMargin: 15,
    "predicted volume per week": 120,
    "uplifts vs base": 20,
  },
  {
    mfr: "K-C",
    cust: "Ocado",
    cat: "BATH TISSUE",
    brd: "ANDREX",
    subBrd: "Andrex Supreme Quilts",
    pid: "Ocado_BATH TISSUE_K-C_07 Andrex BT Quilted 4 Roll",
    ppg: "07 Andrex BT Quilted 4 Roll",
    section: "base",
    priceperpiece: 0.6,
    priceperpack: 12,
    "AvgBaseVolume(Packs)": 90,
    "AvgBaseVolume(Piece)": 180,
    PromoPeriod: "2023-12-01 to 2023-12-31",
    PromoPrice: 9,
    RetailersMargin: 18,
    "predicted volume per week": 110,
    "uplifts vs base": 15,
  },
  {
    mfr: "ALL OTHER",
    cust: "Ocado",
    cat: "DIAPERS & PANTS",
    brd: "ALL OTHER",
    subBrd: "Pura",
    pid: "Ocado_DIAPERS & PANTS_ALL OTHER_Baby Diapers (Open) PURA 33",
    ppg: "Baby Diapers (Open) PURA 33",
    section: "base",
    priceperpiece: 0.4,
    priceperpack: 8,
    "AvgBaseVolume(Packs)": 80,
    "AvgBaseVolume(Piece)": 160,
    PromoPeriod: "2023-10-01 to 2023-10-31",
    PromoPrice: 7,
    RetailersMargin: 12,
    "predicted volume per week": 100,
    "uplifts vs base": 10,
  },
  {
    mfr: "K-C",
    cust: "Asda",
    cat: "BABY WIPES",
    brd: "HUGGIES",
    subBrd: "Huggies Pure Extra Care",
    pid: "Asda_BABY WIPES_K-C_09 Hg BW Pure Premium refill P3x4",
    ppg: "09 Hg BW Pure Premium refill P3x4",
    section: "base",
    priceperpiece: 0.5,
    priceperpack: 10,
    "AvgBaseVolume(Packs)": 100,
    "AvgBaseVolume(Piece)": 200,
    PromoPeriod: "2023-11-01 to 2023-11-30",
    PromoPrice: 8,
    RetailersMargin: 15,
    "predicted volume per week": 120,
    "uplifts vs base": 20,
  },
  {
    mfr: "K-C",
    cust: "Morrisons Group",
    cat: "BATH TISSUE",
    brd: "ANDREX",
    subBrd: "Andrex Classic Clean",
    pid: "Morrisons Group_BATH TISSUE_K-C_07 Andrex Toilet Tissue 12 Roll",
    ppg: "07 Andrex Toilet Tissue 12 Roll",
    section: "base",
    priceperpiece: 0.6,
    priceperpack: 12,
    "AvgBaseVolume(Packs)": 90,
    "AvgBaseVolume(Piece)": 180,
    PromoPeriod: "2023-12-01 to 2023-12-31",
    PromoPrice: 9,
    RetailersMargin: 18,
    "predicted volume per week": 110,
    "uplifts vs base": 15,
  },
  {
    mfr: "K-C",
    cust: "Ocado",
    cat: "BABY WIPES",
    brd: "HUGGIES",
    subBrd: "Pure",
    pid: "Ocado_BABY WIPES_K-C_09 Huggies Wipes Pure P18x1",
    ppg: "09 Huggies Wipes Pure P18x1",
    section: "base",
    priceperpiece: 0.4,
    priceperpack: 8,
    "AvgBaseVolume(Packs)": 80,
    "AvgBaseVolume(Piece)": 160,
    PromoPeriod: "2023-10-01 to 2023-10-31",
    PromoPrice: 7,
    RetailersMargin: 12,
    "predicted volume per week": 100,
    "uplifts vs base": 10,
  },
  {
    mfr: "P&G",
    cust: "Sainsbury Superstores",
    cat: "DIAPERS & PANTS",
    brd: "NINJAMAS",
    subBrd: "Pyjama Pants",
    pid: "Sainsbury Superstores_DIAPERS & PANTS_P&G_Youth Pants (Bedwetting Pants) PYJAMA PANTS 10",
    ppg: "Youth Pants (Bedwetting Pants) PYJAMA PANTS 10",
    section: "base",
    priceperpiece: 0.5,
    priceperpack: 10,
    "AvgBaseVolume(Packs)": 100,
    "AvgBaseVolume(Piece)": 200,
    PromoPeriod: "2023-11-01 to 2023-11-30",
    PromoPrice: 8,
    RetailersMargin: 15,
    "predicted volume per week": 120,
    "uplifts vs base": 20,
  },
  {
    mfr: "ALL OTHER",
    cust: "Ocado",
    cat: "BABY WIPES",
    brd: "ALL OTHER",
    subBrd: "All Other",
    pid: "Ocado_BABY WIPES_ALL OTHER_Baby Wipes Ocado ALL OTHER 16",
    ppg: "Baby Wipes Ocado ALL OTHER 16",
    section: "base",
    priceperpiece: 0.6,
    priceperpack: 12,
    "AvgBaseVolume(Packs)": 90,
    "AvgBaseVolume(Piece)": 180,
    PromoPeriod: "2023-12-01 to 2023-12-31",
    PromoPrice: 9,
    RetailersMargin: 18,
    "predicted volume per week": 110,
    "uplifts vs base": 15,
  },
  {
    mfr: "ALL OTHER",
    cust: "Sainsbury Superstores",
    cat: "FACIAL TISSUE",
    brd: "WET ONES",
    subBrd: "Wet Ones Be Gentle",
    pid: "Sainsbury Superstores_FACIAL TISSUE_ALL OTHER_Wet Wipes Sainsbury Superstores WET ONES BE GENTLE 1",
    ppg: "Wet Wipes Sainsbury Superstores WET ONES BE GENTLE 1",
    section: "base",
    priceperpiece: 0.4,
    priceperpack: 8,
    "AvgBaseVolume(Packs)": 80,
    "AvgBaseVolume(Piece)": 160,
    PromoPeriod: "2023-10-01 to 2023-10-31",
    PromoPrice: 7,
    RetailersMargin: 12,
    "predicted volume per week": 100,
    "uplifts vs base": 10,
  },
  {
    mfr: "P&G",
    cust: "Ocado",
    cat: "BABY WIPES",
    brd: "PAMPERS",
    subBrd: "Coco Harmonie",
    pid: "Ocado_BABY WIPES_P&G_COCO HARMONIE 1",
    ppg: "COCO HARMONIE 1",
    section: "base",
    priceperpiece: 0.5,
    priceperpack: 10,
    "AvgBaseVolume(Packs)": 100,
    "AvgBaseVolume(Piece)": 200,
    PromoPeriod: "2023-11-01 to 2023-11-30",
    PromoPrice: 8,
    RetailersMargin: 15,
    "predicted volume per week": 120,
    "uplifts vs base": 20,
  },
  {
    mfr: "ALL OTHER",
    cust: "National",
    cat: "DIAPERS & PANTS",
    brd: "ALL OTHER",
    subBrd: "Pura",
    pid: "National_DIAPERS & PANTS_ALL OTHER_Baby Diapers (Open) PURA 33",
    ppg: "Baby Diapers (Open) PURA 33",
    section: "base",
    priceperpiece: 0.6,
    priceperpack: 12,
    "AvgBaseVolume(Packs)": 90,
    "AvgBaseVolume(Piece)": 180,
    PromoPeriod: "2023-12-01 to 2023-12-31",
    PromoPrice: 9,
    RetailersMargin: 18,
    "predicted volume per week": 110,
    "uplifts vs base": 15,
  },
  {
    mfr: "K-C",
    cust: "Sainsbury Local",
    cat: "BABY WIPES",
    brd: "HUGGIES",
    subBrd: "Pure",
    pid: "Sainsbury Local_BABY WIPES_K-C_09 Hg Wipes Pure P4 x 3 Quad",
    ppg: "09 Hg Wipes Pure P4 x 3 Quad",
    section: "base",
    priceperpiece: 0.4,
    priceperpack: 8,
    "AvgBaseVolume(Packs)": 80,
    "AvgBaseVolume(Piece)": 160,
    PromoPeriod: "2023-10-01 to 2023-10-31",
    PromoPrice: 7,
    RetailersMargin: 12,
    "predicted volume per week": 100,
    "uplifts vs base": 10,
  },
  {
    mfr: "P&G",
    cust: "Ocado",
    cat: "DIAPERS & PANTS",
    brd: "PAMPERS",
    subBrd: "Nappy Pants",
    pid: "Ocado_DIAPERS & PANTS_P&G_Diaper Pants (Closed) NAPPY PANTS 27",
    ppg: "Diaper Pants (Closed) NAPPY PANTS 27",
    section: "base",
    priceperpiece: 0.5,
    priceperpack: 10,
    "AvgBaseVolume(Packs)": 100,
    "AvgBaseVolume(Piece)": 200,
    PromoPeriod: "2023-11-01 to 2023-11-30",
    PromoPrice: 8,
    RetailersMargin: 15,
    "predicted volume per week": 120,
    "uplifts vs base": 20,
  },
  {
    mfr: "PRIVATE LABEL",
    cust: "Sainsbury Local",
    cat: "FACIAL TISSUE",
    brd: "PRIVATE LABEL",
    subBrd: "Pl All Other",
    pid: "Sainsbury Local_FACIAL TISSUE_PRIVATE LABEL_Pocket Sainsbury Local PL All Other 10",
    ppg: "Pocket Sainsbury Local PL All Other 10",
    section: "base",
    priceperpiece: 0.6,
    priceperpack: 12,
    "AvgBaseVolume(Packs)": 90,
    "AvgBaseVolume(Piece)": 180,
    PromoPeriod: "2023-12-01 to 2023-12-31",
    PromoPrice: 9,
    RetailersMargin: 18,
    "predicted volume per week": 110,
    "uplifts vs base": 15,
  },
  {
    mfr: "P&G",
    cust: "Morrisons Group",
    cat: "BABY WIPES",
    brd: "PAMPERS",
    subBrd: "Pampers Sensitive",
    pid: "Morrisons Group_BABY WIPES_P&G_PAMPERS SENSITIVE 1",
    ppg: "PAMPERS SENSITIVE 1",
    section: "base",
    priceperpiece: 0.4,
    priceperpack: 8,
    "AvgBaseVolume(Packs)": 80,
    "AvgBaseVolume(Piece)": 160,
    PromoPeriod: "2023-10-01 to 2023-10-31",
    PromoPrice: 7,
    RetailersMargin: 12,
    "predicted volume per week": 100,
    "uplifts vs base": 10,
  },
  {
    mfr: "K-C",
    cust: "Sainsbury Superstores",
    cat: "BABY WIPES",
    brd: "HUGGIES",
    subBrd: "Pure",
    pid: "Sainsbury Superstores_BABY WIPES_K-C_09 Huggies Wipes Pure P12x1",
    ppg: "09 Huggies Wipes Pure P12x1",
    section: "base",
    priceperpiece: 0.5,
    priceperpack: 10,
    "AvgBaseVolume(Packs)": 100,
    "AvgBaseVolume(Piece)": 200,
    PromoPeriod: "2023-11-01 to 2023-11-30",
    PromoPrice: 8,
    RetailersMargin: 15,
    "predicted volume per week": 120,
    "uplifts vs base": 20,
  },
  {
    mfr: "P&G",
    cust: "Tesco Extra",
    cat: "DIAPERS & PANTS",
    brd: "PAMPERS",
    subBrd: "Premium Protection",
    pid: "Tesco Extra_DIAPERS & PANTS_P&G_Baby Diapers (Open) PREMIUM PROTECTION 48",
    ppg: "Baby Diapers (Open) PREMIUM PROTECTION 48",
    section: "base",
    priceperpiece: 0.6,
    priceperpack: 12,
    "AvgBaseVolume(Packs)": 90,
    "AvgBaseVolume(Piece)": 180,
    PromoPeriod: "2023-12-01 to 2023-12-31",
    PromoPrice: 9,
    RetailersMargin: 18,
    "predicted volume per week": 110,
    "uplifts vs base": 15,
  },
  {
    mfr: "ESSITY",
    cust: "Waitrose",
    cat: "BATH TISSUE",
    brd: "CUSHELLE",
    subBrd: "Quilted Coconut",
    pid: "Waitrose_BATH TISSUE_ESSITY_QUILTED COCONUT 6",
    ppg: "QUILTED COCONUT 6",
    section: "base",
    priceperpiece: 0.4,
    priceperpack: 8,
    "AvgBaseVolume(Packs)": 80,
    "AvgBaseVolume(Piece)": 160,
    PromoPeriod: "2023-10-01 to 2023-10-31",
    PromoPrice: 7,
    RetailersMargin: 12,
    "predicted volume per week": 100,
    "uplifts vs base": 10,
  },
  {
    mfr: "K-C",
    cust: "Asda",
    cat: "BATH TISSUE",
    brd: "ANDREX",
    subBrd: "Andrex Classic Clean",
    pid: "Asda_BATH TISSUE_K-C_07 Andrex Toilet Tissue 12 Roll Mega",
    ppg: "07 Andrex Toilet Tissue 12 Roll Mega",
    section: "base",
    priceperpiece: 0.5,
    priceperpack: 10,
    "AvgBaseVolume(Packs)": 100,
    "AvgBaseVolume(Piece)": 200,
    PromoPeriod: "2023-11-01 to 2023-11-30",
    PromoPrice: 8,
    RetailersMargin: 15,
    "predicted volume per week": 120,
    "uplifts vs base": 20,
  },
  {
    mfr: "K-C",
    cust: "National",
    cat: "BABY WIPES",
    brd: "HUGGIES",
    subBrd: "Pure",
    pid: "National_BABY WIPES_K-C_09 Hg Wipes Pure P4 x 3 Quad",
    ppg: "09 Hg Wipes Pure P4 x 3 Quad",
    section: "base",
    priceperpiece: 0.6,
    priceperpack: 12,
    "AvgBaseVolume(Packs)": 90,
    "AvgBaseVolume(Piece)": 180,
    PromoPeriod: "2023-12-01 to 2023-12-31",
    PromoPrice: 9,
    RetailersMargin: 18,
    "predicted volume per week": 110,
    "uplifts vs base": 15,
  },
  {
    mfr: "K-C",
    cust: "Ocado",
    cat: "BATH TISSUE",
    brd: "ANDREX",
    subBrd: "Andrex Skin Kind Washlets",
    pid: "Ocado_BATH TISSUE_K-C_09 Andrex Skin Kind Moist TT P4x3",
    ppg: "09 Andrex Skin Kind Moist TT P4x3",
    section: "base",
    priceperpiece: 0.4,
    priceperpack: 8,
    "AvgBaseVolume(Packs)": 80,
    "AvgBaseVolume(Piece)": 160,
    PromoPeriod: "2023-10-01 to 2023-10-31",
    PromoPrice: 7,
    RetailersMargin: 12,
    "predicted volume per week": 100,
    "uplifts vs base": 10,
  },
  {
    mfr: "ALL OTHER",
    cust: "National",
    cat: "BATH TISSUE",
    brd: "ALL OTHER",
    subBrd: "All Other",
    pid: "National_BATH TISSUE_ALL OTHER_Dry Toilet Tissue National ALL OTHER 4",
    ppg: "Dry Toilet Tissue National ALL OTHER 4",
    section: "base",
    priceperpiece: 0.5,
    priceperpack: 10,
    "AvgBaseVolume(Packs)": 100,
    "AvgBaseVolume(Piece)": 200,
    PromoPeriod: "2023-11-01 to 2023-11-30",
    PromoPrice: 8,
    RetailersMargin: 15,
    "predicted volume per week": 120,
    "uplifts vs base": 20,
  },
  {
    mfr: "K-C",
    cust: "Tesco Superstores",
    cat: "BABY WIPES",
    brd: "HUGGIES",
    subBrd: "Huggies Pure Biodegradable",
    pid: "Tesco Superstores_BABY WIPES_K-C_09 Huggies Biodegradable Wipes 48sc P1x12",
    ppg: "09 Huggies Biodegradable Wipes 48sc P1x12",
    section: "base",
    priceperpiece: 0.6,
    priceperpack: 12,
    "AvgBaseVolume(Packs)": 90,
    "AvgBaseVolume(Piece)": 180,
    PromoPeriod: "2023-12-01 to 2023-12-31",
    PromoPrice: 9,
    RetailersMargin: 18,
    "predicted volume per week": 110,
    "uplifts vs base": 15,
  },
  {
    mfr: "K-C",
    cust: "National",
    cat: "FACIAL TISSUE",
    brd: "KLEENEX",
    subBrd: "Kleenex Balsam",
    pid: "National_FACIAL TISSUE_K-C_09 Klx Bals Mln P2x6",
    ppg: "09 Klx Bals Mln P2x6",
    section: "base",
    priceperpiece: 0.4,
    priceperpack: 8,
    "AvgBaseVolume(Packs)": 80,
    "AvgBaseVolume(Piece)": 160,
    PromoPeriod: "2023-10-01 to 2023-10-31",
    PromoPrice: 7,
    RetailersMargin: 12,
    "predicted volume per week": 100,
    "uplifts vs base": 10,
  },
  {
    mfr: "P&G",
    cust: "Sainsbury",
    cat: "DIAPERS & PANTS",
    brd: "PAMPERS",
    subBrd: "Nappy Pants",
    pid: "Sainsbury_DIAPERS & PANTS_P&G_Diaper Pants (Closed) NAPPY PANTS 40",
    ppg: "Diaper Pants (Closed) NAPPY PANTS 40",
    section: "base",
    priceperpiece: 0.5,
    priceperpack: 10,
    "AvgBaseVolume(Packs)": 100,
    "AvgBaseVolume(Piece)": 200,
    PromoPeriod: "2023-11-01 to 2023-11-30",
    PromoPrice: 8,
    RetailersMargin: 15,
    "predicted volume per week": 120,
    "uplifts vs base": 20,
  },
  {
    mfr: "ALL OTHER",
    cust: "Sainsbury Local",
    cat: "FACIAL TISSUE",
    brd: "ALL OTHER",
    subBrd: "All Other",
    pid: "Sainsbury Local_FACIAL TISSUE_ALL OTHER_Pocket Sainsbury Local ALL OTHER 1",
    ppg: "Pocket Sainsbury Local ALL OTHER 1",
    section: "base",
    priceperpiece: 0.6,
    priceperpack: 12,
    "AvgBaseVolume(Packs)": 90,
    "AvgBaseVolume(Piece)": 180,
    PromoPeriod: "2023-12-01 to 2023-12-31",
    PromoPrice: 9,
    RetailersMargin: 18,
    "predicted volume per week": 110,
    "uplifts vs base": 15,
  },
  {
    mfr: "P&G",
    cust: "Ocado",
    cat: "DIAPERS & PANTS",
    brd: "PAMPERS",
    subBrd: "Nappy Pants",
    pid: "Ocado_DIAPERS & PANTS_P&G_Diaper Pants (Closed) NAPPY PANTS 54",
    ppg: "Diaper Pants (Closed) NAPPY PANTS 54",
    section: "base",
    priceperpiece: 0.4,
    priceperpack: 8,
    "AvgBaseVolume(Packs)": 80,
    "AvgBaseVolume(Piece)": 160,
    PromoPeriod: "2023-10-01 to 2023-10-31",
    PromoPrice: 7,
    RetailersMargin: 12,
    "predicted volume per week": 100,
    "uplifts vs base": 10,
  },
  {
    mfr: "K-C",
    cust: "Asda",
    cat: "BATH TISSUE",
    brd: "ANDREX",
    subBrd: "Andrex Moist",
    pid: "Asda_BATH TISSUE_K-C_09 Andrex Pure Care Moist TT P1x12",
    ppg: "09 Andrex Pure Care Moist TT P1x12",
    section: "base",
    priceperpiece: 0.5,
    priceperpack: 10,
    "AvgBaseVolume(Packs)": 100,
    "AvgBaseVolume(Piece)": 200,
    PromoPeriod: "2023-11-01 to 2023-11-30",
    PromoPrice: 8,
    RetailersMargin: 15,
    "predicted volume per week": 120,
    "uplifts vs base": 20,
  },
  {
    mfr: "PRIVATE LABEL",
    cust: "Sainsbury Superstores",
    cat: "FACIAL TISSUE",
    brd: "PRIVATE LABEL",
    subBrd: "Pl All Other",
    pid: "Sainsbury Superstores_FACIAL TISSUE_PRIVATE LABEL_Boxes Sainsbury Superstores PL All Other 1",
    ppg: "Boxes Sainsbury Superstores PL All Other 1",
    section: "base",
    priceperpiece: 0.6,
    priceperpack: 12,
    "AvgBaseVolume(Packs)": 90,
    "AvgBaseVolume(Piece)": 180,
    PromoPeriod: "2023-12-01 to 2023-12-31",
    PromoPrice: 9,
    RetailersMargin: 18,
    "predicted volume per week": 110,
    "uplifts vs base": 15,
  },
  {
    mfr: "ALL OTHER",
    cust: "Ocado",
    cat: "FACIAL TISSUE",
    brd: "WET ONES",
    subBrd: "Wet Ones Be Gentle",
    pid: "Ocado_FACIAL TISSUE_ALL OTHER_Wet Wipes Ocado WET ONES BE GENTLE 1",
    ppg: "Wet Wipes Ocado WET ONES BE GENTLE 1",
    section: "base",
    priceperpiece: 0.4,
    priceperpack: 8,
    "AvgBaseVolume(Packs)": 80,
    "AvgBaseVolume(Piece)": 160,
    PromoPeriod: "2023-10-01 to 2023-10-31",
    PromoPrice: 7,
    RetailersMargin: 12,
    "predicted volume per week": 100,
    "uplifts vs base": 10,
  },
  {
    mfr: "P&G",
    cust: "Tesco Extra",
    cat: "DIAPERS & PANTS",
    brd: "PAMPERS",
    subBrd: "Premium Protection New Baby",
    pid: "Tesco Extra_DIAPERS & PANTS_P&G_Baby Diapers (Open) PREMIUM PROTECTION NEW BABY 40",
    ppg: "Baby Diapers (Open) PREMIUM PROTECTION NEW BABY 40",
    section: "base",
    priceperpiece: 0.5,
    priceperpack: 10,
    "AvgBaseVolume(Packs)": 100,
    "AvgBaseVolume(Piece)": 200,
    PromoPeriod: "2023-11-01 to 2023-11-30",
    PromoPrice: 8,
    RetailersMargin: 15,
    "predicted volume per week": 120,
    "uplifts vs base": 20,
  },
  {
    mfr: "K-C",
    cust: "Total Co-ops",
    cat: "BATH TISSUE",
    brd: "ANDREX",
    subBrd: "Andrex Classic Clean Washlets",
    pid: "Total Co-ops_BATH TISSUE_K-C_09 Andrex Moist Refill x 12",
    ppg: "09 Andrex Moist Refill x 12",
    section: "base",
    priceperpiece: 0.6,
    priceperpack: 12,
    "AvgBaseVolume(Packs)": 90,
    "AvgBaseVolume(Piece)": 180,
    PromoPeriod: "2023-12-01 to 2023-12-31",
    PromoPrice: 9,
    RetailersMargin: 18,
    "predicted volume per week": 110,
    "uplifts vs base": 15,
  },
  {
    mfr: "P&G",
    cust: "Ocado",
    cat: "BABY WIPES",
    brd: "PAMPERS",
    subBrd: "Pampers Sensitive",
    pid: "Ocado_BABY WIPES_P&G_PAMPERS SENSITIVE 4",
    ppg: "PAMPERS SENSITIVE 4",
    section: "base",
    priceperpiece: 0.4,
    priceperpack: 8,
    "AvgBaseVolume(Packs)": 80,
    "AvgBaseVolume(Piece)": 160,
    PromoPeriod: "2023-10-01 to 2023-10-31",
    PromoPrice: 7,
    RetailersMargin: 12,
    "predicted volume per week": 100,
    "uplifts vs base": 10,
  },
];

export default mockData;
